main : g++ - g main.cpp - std = c++ 98 - pedantic -
                                o main

                                    clean : rm -
                                            f *.o *
                                                    .tar
                                                    .gz main reset clear

                                                        run :./
                                                main

                                                    tar
    : tar - cvz SortNode.*SortList.*-f DoublyLinkedList.tar.gz