task2 : board.o piece.o main.o g++ board.o piece.o main.o -
    o task2

        board.o : board.cpp g++ -
    c board
        .cpp

            piece.o : piece.cpp g++ -
    c piece
        .cpp

            main.o : main.cpp g++ -
    c main.cpp

            run
    :./ task2

            clean : rm *.o task2
